export enum ORDER_STATUS {
  PENDING_RESPONSE = 'PENDING_RESPONSE',
  PLANTATION_DECLINED = 'PLANTATION_DECLINED',
  PLANTATION_APPROVED = 'PLANTATION_APPROVED',
  KARGO_DECLINED = 'KARGO_DECLINED',
  IN_DELIVERY = 'IN_DELIVERY'
}
